version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/qry
    steps:
      - checkout
      - run: make test
      - run: go get -u github.com/mgechev/revive && go get -u github.com/securego/gosec/v2/cmd/gosec
      - run: make lint
      - store_artifacts:
          path: coverage.out
          destination: coverage.out
      - codecov/upload:
          file: coverage.out