ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = -1
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.deep-exit]
[rule.empty-lines]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.if-return]
[rule.increment-decrement]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.struct-tag]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.cyclomatic]
  arguments =[10]
[rule.line-length-limit]
  arguments =[140]
[rule.argument-limit]
  arguments =[3]